header = """
/* filecoin_proofs_ffi Header */

#ifdef __cplusplus
extern "C" {{
#endif
"""
trailer = """
#ifdef __cplusplus
} /* extern "C" */
#endif
"""

include_guard = "FILECOIN_PROOFS_FFI_H"
include_version = true
language = "C"

[export]
prefix = "filecoin_proofs_ffi"

[parse]
parse_deps = false
